--CREATING A ROLE TO BE GIVEN TO A USER THAT IS A DOCTOR WITH A DEFUALT PASSWORD
CREATE ROLE doctor IDENTIFIED BY iamdoctor;
-- GRANTING SOME SYSTEM PRIVILAGES THAT A ROLE DOCTOR CAN WORK WITH
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, 
DELETE ANY TABLE TO DOCTOR;
-- GRANTING TABLE PRIVILAGES THAT THE ROLE NEEDS TO WORK WITH 
-- OF A SPECIFIC TABLE CALLED DOCTOR TABLE
GRANT SELECT, INSERT, UPDATE, DELETE ON dr_table TO DOCTOR;
-- also GRANTING TABLE PRIVILAGES OF A PATIENT RECORD TABLE
GRANT SELECT, INSERT, UPDATE, DELETE ON rec_table TO DOCTOR;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A PATIENT RECORD TYPE 
GRANT EXECUTE ON p_record TO DOCTOR;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A DOCTOR TYPE 
GRANT EXECUTE, DEBUG ON doctor_typ TO DOCTOR;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A ADDRESS TYPE 
GRANT EXECUTE, DEBUG ON address_typ TO DOCTOR;


--CREATING A ROLE TO BE GIVEN TO A USER THAT IS A NURSE WITH A DEFUALT PASSWORD
CREATE ROLE nurse IDENTIFIED BY iamnurse;
-- GRANTING SOME SYSTEM PRIVILAGES THAT A ROLE NURSE CAN WORK WITH
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, 
DELETE ANY TABLE TO NURSE;
-- GRANTING TABLE PRIVILAGES THAT THE ROLE NEEDS TO WORK WITH 
-- OF A SPECIFIC TABLE CALLED NURSE TABLE
GRANT SELECT, INSERT, UPDATE, DELETE ON NURSE_table TO NURSE;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A NURSE TYPE
GRANT EXECUTE ON nurse_typ TO NURSE;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A ADDRESS TYPE 
GRANT EXECUTE, DEBUG ON address_typ TO NURSE;

--CREATING A ROLE TO BE GIVEN TO A USER THAT IS A PATIENT WITH A DEFUALT PASSWORD
CREATE ROLE patient IDENTIFIED BY iampatient;
-- GRANTING SOME SYSTEM PRIVILAGES THAT A ROLE PATIENT CAN WORK WITH
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, 
DELETE ANY TABLE TO PATIENT;
-- GRANTING TABLE PRIVILAGES THAT THE ROLE NEEDS TO WORK WITH 
-- OF A SPECIFIC TABLE CALLED PATIENT TABLE
GRANT SELECT, INSERT, UPDATE, DELETE ON patient_table TO PATIENT;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A PATIENT TYPE
GRANT EXECUTE ON patient_typ TO PATIENT;
-- GRANTING OF OBJECT PRIVILAGE EXECUTE TO A BODY OF A ADDRESS TYPE 
GRANT EXECUTE, DEBUG ON address_typ TO PATIENT;


-- Creating a demo doctor with name abebe with a password
CREATE USER ABEBE identified by abebeisdoctor;

-- Granting DOCTOR role to the user we've just created
GRANT DOCTOR TO abebe;


